Set-Location 'd:\OneDrive\WIP\Sources\Intense.2020\D+AI'
$code = @'
; Test enum alignment
XIncludeFile "c2-inc-v17.pbi"
OpenConsole()

PrintN("LLPMOV_DEPRECATED = " + Str(#ljLLPMOV_DEPRECATED))
PrintN("INC_VAR = " + Str(#ljINC_VAR))
PrintN("INC_VAR_POST = " + Str(#ljINC_VAR_POST))
PrintN("LDECV_PRE = " + Str(#ljLDEC_VAR_PRE))
PrintN("INCP_PRE = " + Str(#ljPTRINC_PRE))
PrintN("DECP_PRE = " + Str(#ljPTRDEC_PRE))
PrintN("INCP_POST = " + Str(#ljPTRINC_POST))
PrintN("DECP_POST = " + Str(#ljPTRDEC_POST))
PrintN("STOSTRUCT = " + Str(#ljSTORE_STRUCT))
PrintN("LSTOSTRUCT = " + Str(#ljLSTORE_STRUCT))
PrintN("ADDASS = " + Str(#ljADD_ASSIGN_VAR))
PrintN("ARRAYFETCH_INT_LOCAL_LOPT = " + Str(#ljARRAYFETCH_INT_LOCAL_LOPT))
PrintN("ARRAYFETCH_FLOAT_LOCAL_LOPT = " + Str(#ljARRAYFETCH_FLOAT_LOCAL_LOPT))
PrintN("ARRAYFETCH_STR_LOCAL_LOPT = " + Str(#ljARRAYFETCH_STR_LOCAL_LOPT))
PrintN("ARRAYSTORE_INT_LOCAL_LOPT_LOPT = " + Str(#ljARRAYSTORE_INT_LOCAL_LOPT_LOPT))
PrintN("ARRAYSTORE_INT_LOCAL_LOPT_OPT = " + Str(#ljARRAYSTORE_INT_LOCAL_LOPT_OPT))
PrintN("ARRAYSTORE_INT_LOCAL_LOPT_STACK = " + Str(#ljARRAYSTORE_INT_LOCAL_LOPT_STACK))
PrintN("ARRAYSTORE_FLOAT_LOCAL_LOPT_LOPT = " + Str(#ljARRAYSTORE_FLOAT_LOCAL_LOPT_LOPT))
PrintN("ARRAYSTORE_FLOAT_LOCAL_LOPT_OPT = " + Str(#ljARRAYSTORE_FLOAT_LOCAL_LOPT_OPT))
PrintN("ARRAYSTORE_FLOAT_LOCAL_LOPT_STACK = " + Str(#ljARRAYSTORE_FLOAT_LOCAL_LOPT_STACK))
PrintN("ARRAYSTORE_STR_LOCAL_LOPT_LOPT = " + Str(#ljARRAYSTORE_STR_LOCAL_LOPT_LOPT))
PrintN("ARRAYSTORE_STR_LOCAL_LOPT_OPT = " + Str(#ljARRAYSTORE_STR_LOCAL_LOPT_OPT))
PrintN("ARRAYSTORE_STR_LOCAL_LOPT_STACK = " + Str(#ljARRAYSTORE_STR_LOCAL_LOPT_STACK))
PrintN("GETADDR = " + Str(#ljGETADDR))
PrintN("GETADDRF = " + Str(#ljGETADDRF))
PrintN("GETADDRS = " + Str(#ljGETADDRS))
PrintN("GETLOCALADDR = " + Str(#ljGETLOCALADDR))
PrintN("GETLOCALADDRF = " + Str(#ljGETLOCALADDRF))
PrintN("GETLOCALADDRS = " + Str(#ljGETLOCALADDRS))
PrintN("PTRFETCH = " + Str(#ljPTRFETCH))
PrintN("PTRFETCH_INT = " + Str(#ljPTRFETCH_INT))
PrintN("PTRFETCH_FLOAT = " + Str(#ljPTRFETCH_FLOAT))
PrintN("PTRFETCH_STR = " + Str(#ljPTRFETCH_STR))
PrintN("PTRSTORE = " + Str(#ljPTRSTORE))
PrintN("PTRSTORE_INT = " + Str(#ljPTRSTORE_INT))
PrintN("PTRSTORE_FLOAT = " + Str(#ljPTRSTORE_FLOAT))
PrintN("PTRSTORE_STR = " + Str(#ljPTRSTORE_STR))
PrintN("PTRFIELD_I = " + Str(#ljPTRFIELD_I))
PrintN("PTRFIELD_F = " + Str(#ljPTRFIELD_F))
PrintN("PTRFIELD_S = " + Str(#ljPTRFIELD_S))
PrintN("nd_StructArrayField_I = " + Str(#nd_StructArrayField_I))
PrintN("nd_StructArrayField_F = " + Str(#nd_StructArrayField_F))
PrintN("nd_StructArrayField_S = " + Str(#nd_StructArrayField_S))
PrintN("PTRADD = " + Str(#ljPTRADD))
PrintN("PTRSUB = " + Str(#ljPTRSUB))
PrintN("GETFUNCADDR = " + Str(#ljGETFUNCADDR))
PrintN("CALLFUNCPTR = " + Str(#ljCALLFUNCPTR))
PrintN("GETARRAYADDR = " + Str(#ljGETARRAYADDR))
PrintN("GETARRAYADDRV = " + Str(#ljGETARRAYADDRF))
PrintN("GETARRAYADDRS = " + Str(#ljGETARRAYADDRS))
PrintN("PMOV = " + Str(#ljPMOV))
PrintN("PFETCH = " + Str(#ljPFETCH))
PrintN("PSTORE = " + Str(#ljPSTORE))
PrintN("PLFETCH_DEPRECATED = " + Str(#ljPLFETCH_DEPRECATED))
PrintN("PLSTORE_DEPRECATED = " + Str(#ljPLSTORE_DEPRECATED))
PrintN("PLMOV_DEPRECATED = " + Str(#ljPLMOV_DEPRECATED))

'@
$code | Set-Content 'test_enum.pb'
& 'D:\WIP\APPS\PureBasic.610\Compilers\pbcompiler.exe' 'test_enum.pb' '-e' 'test_enum.exe' '--console'
./test_enum.exe
